on: [push, pull_request]

jobs:
  aplicationTests:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão
        uses: actions/setup-node@v1
        with:
          node-version: 16.16

      - name: instalando dependências
        run: npm i ./back-end

      - name: executando o lint para verificar os erros do back
        run: npx eslint ./back-end

      - name: executando o lint para verificar os erros do front
        run: npm eslint ./front-end
        
      - name: executando testes de integração do back-end
        run: npm run test:back-end
  