on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão
        uses: actions/setup-node@v1
        with:
          node-version: 16.16

      - name: instalando dependências
        run: npm i ./back-end

      - name: executando o lint para verificar erros
        run: npx eslint ./back-end

  integrationTest:
    runs-on: ubuntu-latest
    needs: [eslint]
    steps:
      - name: executando testes de integração
        run: cd back-end && npm test